In [1]:
import numpy as np

In [2]:
#task1
ratings = np.array([
    [4, 5, 3, 4, 2],
    [5, 4, 4, 3, 5],
    [3, 5, 5, 4, 4],
    [4, 3, 2, 5, 4]
])

print("All Ratings:")
print(ratings)
selected_users = ratings[1:3]

print("\nRatings of 2nd and 3rd Users:")
print(selected_users)

All Ratings:
[[4 5 3 4 2]
 [5 4 4 3 5]
 [3 5 5 4 4]
 [4 3 2 5 4]]

Ratings of 2nd and 3rd Users:
[[5 4 4 3 5]
 [3 5 5 4 4]]


In [3]:
#task2
steps = np.array([7500, 8200, 9000, 6500, 10000,
                  7800, 8500, 9200, 7000, 11000])

high_steps = steps[steps > 8000]

print("\nDays with Steps Greater Than 8000:")
print(high_steps)


Days with Steps Greater Than 8000:
[ 8200  9000 10000  8500  9200 11000]


In [4]:
#task3
scores = np.array([180, 195, 210, 175, 220, 190, 205, 185])

selected_scores = scores[[1, 4, 6]]  # Matches 2, 5, and 7

print("\nScores from Matches 2, 5, and 7:")
print(selected_scores)



Scores from Matches 2, 5, and 7:
[195 220 205]


In [10]:
#task4
prices = np.array([999, 1499, 2499, 3999, 5999])

discounted_prices = prices * 0.90  # 10% discount

print("\nOriginal Prices:")
print(prices)

print("Prices After 10% Discount:")
print(discounted_prices)


Original Prices:
[ 999 1499 2499 3999 5999]
Prices After 10% Discount:
[ 899.1 1349.1 2249.1 3599.1 5399.1]


In [11]:
#task5
song_ratings = np.array([5, -2, 3, -1, 0, 4, -3])

song_ratings[song_ratings < 0] = 0

print("\nRatings After Replacing Negatives with 0:")
print(song_ratings)


Ratings After Replacing Negatives with 0:
[5 0 3 0 0 4 0]
