In [1]:
#task1
import numpy as np

In [7]:
#task2
followers = np.array([1200, 15000, 67000, 340000, 1250000])

print("Followers Array:", followers)
print("Shape:", followers.shape)
print("Dimensions:", followers.ndim)
print("Data Type:", followers.dtype)


Followers Array: [   1200   15000   67000  340000 1250000]
Shape: (5,)
Dimensions: 1
Data Type: int64


In [6]:
#task3
order_ids = np.arange(101, 111)

print("Order IDs:", order_ids)
print("Size:", order_ids.size)


Order IDs: [101 102 103 104 105 106 107 108 109 110]
Size: 10


In [4]:
#task4
like_matrix = np.eye(3)

print("Like Identity Matrix:")
print(like_matrix)


Like Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#task5
scores_list = [45, 67, 120, 89, 54]
scores_array = np.array(scores_list)

print("Cricket Scores:", scores_array)
print("Bytes per score:", scores_array.itemsize)


Cricket Scores: [ 45  67 120  89  54]
Bytes per score: 8
